<?php

declare(strict_types=1);

namespace Cbox\TelemetryUi\Panels\Builtin;

use Cbox\TelemetryUi\Connectors\SourceException;
use Cbox\TelemetryUi\Panels\Panel;
use Cbox\TelemetryUi\Panels\Ui;
use Cbox\TelemetryUi\Queries\Ir\MetricQuery;
use Cbox\TelemetryUi\Support\Format;
use Cbox\TelemetryUi\Support\ServiceIdentity;

/**
 * Service relations from Tempo's metrics-generator service graphs:
 * client → server edges with volume, failures and p95 — the map of who
 * calls whom across proxies, Beyla-instrumented infra and apps.
 */
final class ServiceGraph extends Panel
{
    public function data(): array
    {
        $p = $this->promDuration();

        $edges = [];
        $error = null;

        try {
            // Generated by Tempo, so these carry client/server labels only —
            // the fleet scope is applied per edge in PHP below.
            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_total'))->increase($p)->sumBy('client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                $edges[$key] = [
                    'client' => $sample->labels['client'] ?? '?',
                    'server' => $sample->labels['server'] ?? '?',
                    'requests' => $sample->value,
                    'failed' => 0.0,
                    'p95' => null,
                ];
            }

            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_failed_total'))->increase($p)->sumBy('client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key])) {
                    $edges[$key]['failed'] = $sample->value;
                }
            }

            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_server_seconds_bucket'))->quantile(0.95, $p, 'client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key]) && ! is_nan($sample->value)) {
                    $edges[$key]['p95'] = $sample->value * 1000;
                }
            }
        } catch (SourceException $exception) {
            $error = $exception->getMessage();
        }

        if ($this->service !== '') {
            $edges = array_filter(
                $edges,
                fn (array $edge): bool => $edge['client'] === $this->service || $edge['server'] === $this->service,
            );
        }

        $edges = array_filter($edges, static fn (array $edge): bool => $edge['requests'] >= 0.5);

        usort($edges, static fn (array $a, array $b): int => $b['requests'] <=> $a['requests']);

        $graph = [
            'kind' => 'graph',
            'title' => 'Service graph',
            'subtitle' => 'Who-calls-whom across proxies, Beyla-instrumented infra and apps (from Tempo)',
            'span' => 2,
            ...$this->graphData($edges),
        ];

        if ($error !== null || $edges === []) {
            return [
                ...$graph,
                'error' => $error,
                'empty' => 'No service-graph edges in this period. Requires Tempo\'s metrics-generator (service-graphs processor) remote-writing to your metrics backend.',
            ];
        }

        $rows = array_map(static fn (array $edge): array => [
            'client' => Ui::cell($edge['client'], ['badge' => $edge['client']]),
            'arrow' => Ui::cell('→', ['tone' => 'dim']),
            'server' => Ui::cell($edge['server'], ['badge' => $edge['server']]),
            'requests' => Ui::cell(Format::count($edge['requests']), ['raw' => $edge['requests'], 'mono' => true]),
            'failed' => Ui::cell(Format::count($edge['failed']), ['raw' => $edge['failed'], 'mono' => true, 'tone' => $edge['failed'] > 0 ? 'danger' : null]),
            'p95' => $edge['p95'] !== null
                ? Ui::cell(Format::ms($edge['p95']), ['raw' => $edge['p95'], 'mono' => true])
                : Ui::cell('—', ['mono' => true]),
        ], $edges);

        return Ui::composite('Service graph', [
            [...$graph, 'title' => ''],
            Ui::table('', [
                Ui::col('client', 'Client'),
                Ui::col('arrow', ''),
                Ui::col('server', 'Server'),
                Ui::num('requests', 'Requests'),
                Ui::num('failed', 'Failed'),
                Ui::num('p95', 'P95'),
            ], $rows),
        ], [
            'subtitle' => $graph['subtitle'],
            'span' => 2,
        ]);
    }

    /**
     * The `graph` payload: one node per service (sized/health-coloured by the
     * traffic it receives) and one edge per client → server relation.
     *
     * @param  list<array{client: string, server: string, requests: float, failed: float, p95: float|null}>  $edges
     * @return array{nodes: list<array{id: string, label: string, kind: string, color: string, requests: float, errors: float}>, edges: list<array{source: string, target: string, count: float, errors: float, p95: float|null}>}
     */
    private function graphData(array $edges): array
    {
        /** @var array<string, bool> $services */
        $services = [];
        /** @var array<string, float> $inbound */
        $inbound = [];
        /** @var array<string, float> $inboundFailed */
        $inboundFailed = [];

        foreach ($edges as $edge) {
            $services[$edge['client']] = true;
            $services[$edge['server']] = true;
            $inbound[$edge['server']] = ($inbound[$edge['server']] ?? 0.0) + $edge['requests'];
            $inboundFailed[$edge['server']] = ($inboundFailed[$edge['server']] ?? 0.0) + $edge['failed'];
        }

        $nodes = [];

        foreach (array_keys($services) as $service) {
            $service = (string) $service;
            $nodes[] = [
                'id' => $service,
                'label' => $service,
                'kind' => ServiceIdentity::kind($service),
                'color' => ServiceIdentity::color($service),
                'requests' => $inbound[$service] ?? 0.0,
                'errors' => $inboundFailed[$service] ?? 0.0,
            ];
        }

        $links = array_map(static fn (array $edge): array => [
            'source' => $edge['client'],
            'target' => $edge['server'],
            'count' => $edge['requests'],
            'errors' => $edge['failed'],
            'p95' => $edge['p95'],
        ], $edges);

        return ['nodes' => $nodes, 'edges' => $links];
    }
}
