<?php

declare(strict_types=1);

namespace Cbox\TelemetryUi\Panels\Builtin;

use Cbox\TelemetryUi\Connectors\SourceException;
use Cbox\TelemetryUi\Panels\Panel;
use Cbox\TelemetryUi\Panels\Ui;
use Cbox\TelemetryUi\Queries\Ir\MetricQuery;
use Cbox\TelemetryUi\Queries\Ir\TraceCondition;
use Cbox\TelemetryUi\Queries\Ir\TraceOp;
use Cbox\TelemetryUi\Support\Format;
use Cbox\TelemetryUi\Support\ServiceIdentity;

/**
 * Service relations from Tempo's metrics-generator service graphs:
 * client → server edges with volume, failures and p95 — the map of who
 * calls whom across proxies, Beyla-instrumented infra and apps.
 *
 * @phpstan-import-type Link from Ui
 */
final class ServiceGraph extends Panel
{
    public function data(): array
    {
        $p = $this->promDuration();

        $edges = [];
        $error = null;

        try {
            // Generated by Tempo, so these carry client/server labels only —
            // the fleet scope is applied per edge in PHP below.
            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_total'))->increase($p)->sumBy('client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                $edges[$key] = [
                    'client' => $sample->labels['client'] ?? '?',
                    'server' => $sample->labels['server'] ?? '?',
                    'requests' => $sample->value,
                    'failed' => 0.0,
                    'p95' => null,
                ];
            }

            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_failed_total'))->increase($p)->sumBy('client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key])) {
                    $edges[$key]['failed'] = $sample->value;
                }
            }

            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_server_seconds_bucket'))->quantile(0.95, $p, 'client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key]) && ! is_nan($sample->value)) {
                    $edges[$key]['p95'] = $sample->value * 1000;
                }
            }
        } catch (SourceException $exception) {
            $error = $exception->getMessage();
        }

        if ($this->service !== '') {
            $edges = array_filter(
                $edges,
                fn (array $edge): bool => $edge['client'] === $this->service || $edge['server'] === $this->service,
            );
        }

        $edges = array_filter($edges, static fn (array $edge): bool => $edge['requests'] >= 0.5);
        $derived = null;

        // No metrics-generator? Derive the map from what the traces already
        // say: every client span is an edge from its service to what it
        // called (another service, a database, a queue, an HTTP host).
        if ($edges === [] && $error === null) {
            [$edges, $derived] = $this->edgesFromSpans();
        }

        usort($edges, static fn (array $a, array $b): int => $b['requests'] <=> $a['requests']);

        $graph = [
            'kind' => 'graph',
            'title' => 'Service graph',
            'subtitle' => $derived === null
                ? 'Who-calls-whom across proxies, Beyla-instrumented infra and apps (from Tempo)'
                : 'Who-calls-whom, derived from sampled client spans — databases, queues and upstream hosts',
            'span' => 2,
            ...$this->graphData($edges),
        ];

        if ($error !== null || $edges === []) {
            return [
                ...$graph,
                'error' => $error,
                'empty' => 'No service-graph edges in this period. Requires Tempo\'s metrics-generator (service-graphs processor) remote-writing to your metrics backend.',
            ];
        }

        $rows = array_map(fn (array $edge): array => [
            '_link' => $this->peerLink($edge['server']),
            'client' => Ui::cell($edge['client'], ['badge' => $edge['client']]),
            'arrow' => Ui::cell('→', ['tone' => 'dim']),
            'server' => Ui::cell($edge['server'], ['badge' => $edge['server']]),
            'requests' => Ui::cell(Format::count($edge['requests']), ['raw' => $edge['requests'], 'mono' => true]),
            'failed' => Ui::cell(Format::count($edge['failed']), ['raw' => $edge['failed'], 'mono' => true, 'tone' => $edge['failed'] > 0 ? 'danger' : null]),
            'p95' => $edge['p95'] !== null
                ? Ui::cell(Format::ms($edge['p95']), ['raw' => $edge['p95'], 'mono' => true])
                : Ui::cell('—', ['mono' => true]),
        ], $edges);

        return Ui::composite('Service graph', [
            [...$graph, 'title' => ''],
            Ui::table('', [
                Ui::col('client', 'Client'),
                Ui::col('arrow', ''),
                Ui::col('server', 'Server'),
                Ui::num('requests', 'Requests'),
                Ui::num('failed', 'Failed'),
                Ui::num('p95', 'P95'),
            ], $rows),
        ], [
            'subtitle' => $graph['subtitle'],
            'span' => 2,
            'note' => $derived !== null ? "Derived from {$derived} sampled client spans; volumes are relative, not totals. Enable Tempo's service-graphs processor for exact edges." : null,
        ]);
    }

    /**
     * Edges from a bounded sample of client spans: service → peer, where the
     * peer is `peer.service`, else the database system, else the messaging
     * system, else the upstream host.
     *
     * @return array{0: list<array{client: string, server: string, requests: float, failed: float, p95: float|null}>, 1: int}
     */
    private function edgesFromSpans(): array
    {
        [$start, $end] = $this->range();

        $select = ['span.peer.service', 'span.db.system.name', 'span.messaging.system', 'span.server.address', 'span.http.response.status_code'];

        try {
            // Client spans (HTTP, queues) — and database spans, which some
            // emitters record as internal rather than client kind.
            $summaries = [
                ...$this->traces()->search($this->traceQuery(TraceCondition::token('kind', TraceOp::Eq, 'client'))->select(...$select), $start, $end, 30),
                ...$this->traces()->search($this->traceQuery(TraceCondition::nil('span.db.system.name'))->select(...$select), $start, $end, 10),
            ];
        } catch (SourceException) {
            return [[], 0];
        }

        $seen = [];

        /** @var array<string, array{client: string, server: string, durations: list<float>, failed: float}> $acc */
        $acc = [];
        $spans = 0;

        foreach ($summaries as $summary) {
            foreach ($summary->matchedSpans as $span) {
                if (isset($seen[$summary->traceId.$span->spanId])) {
                    continue; // a db span of kind client matches both searches
                }

                $seen[$summary->traceId.$span->spanId] = true;
                $a = $span->attributes;
                $peer = match (true) {
                    is_scalar($a['peer.service'] ?? null) && (string) $a['peer.service'] !== '' => (string) $a['peer.service'],
                    is_scalar($a['db.system.name'] ?? null) && (string) $a['db.system.name'] !== '' => 'db:'.$a['db.system.name'],
                    is_scalar($a['messaging.system'] ?? null) && (string) $a['messaging.system'] !== '' => 'queue:'.$a['messaging.system'],
                    is_scalar($a['server.address'] ?? null) && (string) $a['server.address'] !== '' => (string) $a['server.address'],
                    default => null,
                };

                if ($peer === null || $summary->rootServiceName === '') {
                    continue;
                }

                $spans++;
                $key = $summary->rootServiceName.'→'.$peer;
                $acc[$key] ??= ['client' => $summary->rootServiceName, 'server' => $peer, 'durations' => [], 'failed' => 0.0];
                $acc[$key]['durations'][] = $span->durationMs;
                $status = $a['http.response.status_code'] ?? null;
                $acc[$key]['failed'] += is_numeric($status) && (int) $status >= 500 ? 1.0 : 0.0;
            }
        }

        $edges = [];

        foreach ($acc as $edge) {
            $durations = $edge['durations'];
            sort($durations);
            $edges[] = [
                'client' => $edge['client'],
                'server' => $edge['server'],
                'requests' => (float) count($durations),
                'failed' => $edge['failed'],
                'p95' => $durations[(int) max(0, ceil(0.95 * count($durations)) - 1)] ?? null,
            ];
        }

        return [$edges, $spans];
    }

    /**
     * The `graph` payload: one node per service (sized/health-coloured by the
     * traffic it receives) and one edge per client → server relation.
     *
     * @param  list<array{client: string, server: string, requests: float, failed: float, p95: float|null}>  $edges
     * @return array{nodes: list<array{id: string, label: string, kind: string, color: string, requests: float, errors: float}>, edges: list<array{source: string, target: string, count: float, errors: float, p95: float|null}>}
     */
    private function graphData(array $edges): array
    {
        /** @var array<string, bool> $services */
        $services = [];
        /** @var array<string, float> $inbound */
        $inbound = [];
        /** @var array<string, float> $inboundFailed */
        $inboundFailed = [];

        foreach ($edges as $edge) {
            $services[$edge['client']] = true;
            $services[$edge['server']] = true;
            $inbound[$edge['server']] = ($inbound[$edge['server']] ?? 0.0) + $edge['requests'];
            $inboundFailed[$edge['server']] = ($inboundFailed[$edge['server']] ?? 0.0) + $edge['failed'];
        }

        $nodes = [];

        foreach (array_keys($services) as $service) {
            $service = (string) $service;
            $nodes[] = [
                'id' => $service,
                'label' => $service,
                'kind' => ServiceIdentity::kind($service),
                'color' => ServiceIdentity::color($service),
                'requests' => $inbound[$service] ?? 0.0,
                'errors' => $inboundFailed[$service] ?? 0.0,
            ];
        }

        $links = array_map(static fn (array $edge): array => [
            'source' => $edge['client'],
            'target' => $edge['server'],
            'count' => $edge['requests'],
            'errors' => $edge['failed'],
            'p95' => $edge['p95'],
        ], $edges);

        return ['nodes' => $nodes, 'edges' => $links];
    }

    /**
     * Where an edge's callee leads: a database or queue → its spans in
     * Explore, a host → the outgoing-host page, a service → its entity page.
     *
     * @return Link
     */
    private function peerLink(string $peer): array
    {
        return match (true) {
            str_starts_with($peer, 'db:') => Ui::explore('traces', ['db.system.name='.substr($peer, 3)]),
            str_starts_with($peer, 'queue:') => Ui::explore('traces', ['messaging.system='.substr($peer, 6)]),
            str_contains($peer, '.') || str_contains($peer, ':') => Ui::entity('outgoing', $peer),
            default => Ui::entity('service', $peer),
        };
    }
}
