<?php

declare(strict_types=1);

namespace Cbox\TelemetryUi\Cards\Builtin;

use Cbox\TelemetryUi\Cards\Card;
use Cbox\TelemetryUi\Connectors\SourceException;
use Cbox\TelemetryUi\Queries\Ir\MetricQuery;
use Cbox\TelemetryUi\Support\ServiceIdentity;
use Illuminate\Contracts\View\View;

/**
 * Service relations from Tempo's metrics-generator service graphs:
 * client → server edges with volume, failures and p95 — the map of who
 * calls whom across proxies, Beyla-instrumented infra and apps.
 */
final class ServiceGraph extends Card
{
    public function render(): View
    {
        $p = $this->promDuration();

        $edges = [];
        $error = null;

        try {
            // Generated by Tempo, so these carry client/server labels only —
            // the fleet scope is applied per edge in PHP below.
            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_total'))->increase($p)->sumBy('client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                $edges[$key] = [
                    'client' => $sample->labels['client'] ?? '?',
                    'server' => $sample->labels['server'] ?? '?',
                    'requests' => $sample->value,
                    'failed' => 0.0,
                    'p95' => null,
                ];
            }

            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_failed_total'))->increase($p)->sumBy('client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key])) {
                    $edges[$key]['failed'] = $sample->value;
                }
            }

            foreach ($this->metrics()->query((new MetricQuery('traces_service_graph_request_server_seconds_bucket'))->quantile(0.95, $p, 'client', 'server')) as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key]) && ! is_nan($sample->value)) {
                    $edges[$key]['p95'] = $sample->value * 1000;
                }
            }
        } catch (SourceException $exception) {
            $error = $exception->getMessage();
        }

        if ($this->service !== '') {
            $edges = array_filter(
                $edges,
                fn (array $edge): bool => $edge['client'] === $this->service || $edge['server'] === $this->service,
            );
        }

        $edges = array_filter($edges, static fn (array $edge): bool => $edge['requests'] >= 0.5);

        usort($edges, static fn (array $a, array $b): int => $b['requests'] <=> $a['requests']);

        /** @var view-string $view */
        $view = 'telemetry-ui::cards.service-graph';

        return view($view, [
            'edges' => $edges,
            'graph' => $this->graphData($edges),
            'error' => $error,
        ]);
    }

    public function color(string $service): string
    {
        return ServiceIdentity::color($service);
    }

    /**
     * Shape the edge list into an ECharts force-graph payload: one node per
     * service (sized/health-coloured by the traffic it receives) and one link
     * per edge (width by volume, red when it's failing).
     *
     * @param  list<array{client: string, server: string, requests: float, failed: float, p95: float|null}>  $edges
     * @return array{nodes: list<array{name: string, value: float, failed: float, color: string}>, links: list<array{source: string, target: string, requests: float, failed: float, p95: float|null, errorRate: float}>}
     */
    private function graphData(array $edges): array
    {
        /** @var array<string, bool> $services */
        $services = [];
        /** @var array<string, float> $inbound */
        $inbound = [];
        /** @var array<string, float> $inboundFailed */
        $inboundFailed = [];

        foreach ($edges as $edge) {
            $services[$edge['client']] = true;
            $services[$edge['server']] = true;
            $inbound[$edge['server']] = ($inbound[$edge['server']] ?? 0.0) + $edge['requests'];
            $inboundFailed[$edge['server']] = ($inboundFailed[$edge['server']] ?? 0.0) + $edge['failed'];
        }

        $nodes = [];

        foreach (array_keys($services) as $service) {
            $nodes[] = [
                'name' => $service,
                'value' => $inbound[$service] ?? 0.0,
                'failed' => $inboundFailed[$service] ?? 0.0,
                'color' => ServiceIdentity::color($service),
            ];
        }

        $links = array_map(static fn (array $edge): array => [
            'source' => $edge['client'],
            'target' => $edge['server'],
            'requests' => $edge['requests'],
            'failed' => $edge['failed'],
            'p95' => $edge['p95'],
            'errorRate' => $edge['requests'] > 0.0 ? $edge['failed'] / $edge['requests'] : 0.0,
        ], $edges);

        return ['nodes' => $nodes, 'links' => $links];
    }
}
