<?php

declare(strict_types=1);

namespace Cbox\TelemetryUi\Cards\Builtin;

use Cbox\TelemetryUi\Cards\Card;
use Cbox\TelemetryUi\Connectors\SourceException;
use Cbox\TelemetryUi\Support\ServiceIdentity;
use Illuminate\Contracts\View\View;

/**
 * Service relations from Tempo's metrics-generator service graphs:
 * client → server edges with volume, failures and p95 — the map of who
 * calls whom across proxies, Beyla-instrumented infra and apps.
 */
final class ServiceGraph extends Card
{
    public function render(): View
    {
        $p = $this->promDuration();

        $edges = [];
        $error = null;

        try {
            // Generated by Tempo, so these carry client/server labels only —
            // the fleet scope is applied per edge in PHP below.
            foreach ($this->metrics()->query('sum by (client, server) (increase(traces_service_graph_request_total['.$p.']))') as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                $edges[$key] = [
                    'client' => $sample->labels['client'] ?? '?',
                    'server' => $sample->labels['server'] ?? '?',
                    'requests' => $sample->value,
                    'failed' => 0.0,
                    'p95' => null,
                ];
            }

            foreach ($this->metrics()->query('sum by (client, server) (increase(traces_service_graph_request_failed_total['.$p.']))') as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key])) {
                    $edges[$key]['failed'] = $sample->value;
                }
            }

            foreach ($this->metrics()->query('histogram_quantile(0.95, sum by (client, server, le) (rate(traces_service_graph_request_server_seconds_bucket['.$p.'])))') as $sample) {
                $key = ($sample->labels['client'] ?? '?').'→'.($sample->labels['server'] ?? '?');

                if (isset($edges[$key]) && ! is_nan($sample->value)) {
                    $edges[$key]['p95'] = $sample->value * 1000;
                }
            }
        } catch (SourceException $exception) {
            $error = $exception->getMessage();
        }

        if ($this->service !== '') {
            $edges = array_filter(
                $edges,
                fn (array $edge): bool => $edge['client'] === $this->service || $edge['server'] === $this->service,
            );
        }

        $edges = array_filter($edges, static fn (array $edge): bool => $edge['requests'] >= 0.5);

        usort($edges, static fn (array $a, array $b): int => $b['requests'] <=> $a['requests']);

        /** @var view-string $view */
        $view = 'telemetry-ui::cards.service-graph';

        return view($view, [
            'edges' => $edges,
            'error' => $error,
        ]);
    }

    public function color(string $service): string
    {
        return ServiceIdentity::color($service);
    }
}
